/**
 * Generate docs/audits/dedupe-near-dupes-2026-04-26.md by re-running Q2 + Q3
 * over the post-Q1-cleanup state of signals. Sorted by amount desc.
 *
 * Output structure:
 *   - YAML decisions block at top (one entry per case, user fills in)
 *   - Q2 cases (fund_name variants)
 *   - Q3 cases (gp variants)
 *
 * Suggested canonical per case:
 *   - Q2 (fund_name): longest variant (typically the form with full legal
 *     suffix + entity descriptor), preserves precision.
 *   - Q3 (gp): most-frequently-used variant across the whole signals table
 *     (treats the most common form as the brand-canonical).
 */

import { Client } from "pg";
import fs from "node:fs";

type Signal = {
  id: string;
  plan_id: string;
  fields: Record<string, unknown> | null;
  commitment_amount_usd: string | number | null;
  confidence: string | number | null;
  prompt_version: string | null;
  document_id: string | null;
  created_at: Date | string;
};

function dateStr(d: Date | string | null | undefined): string {
  if (!d) return "";
  const iso = d instanceof Date ? d.toISOString() : String(d);
  return iso.slice(0, 10);
}

type Plan = { id: string; name: string };

function gpOf(s: Signal): string {
  const v = (s.fields ?? {})["gp"];
  return typeof v === "string" ? v : "";
}
function fundOf(s: Signal): string {
  const v = (s.fields ?? {})["fund_name"];
  return typeof v === "string" ? v : "";
}
function approvalOf(s: Signal): string {
  const v = (s.fields ?? {})["approval_date"];
  return typeof v === "string" ? v : "";
}
function fmtAmt(amt: number | string | null): string {
  if (amt == null) return "—";
  const n = typeof amt === "number" ? amt : Number(amt);
  return `$${(n / 1e6).toFixed(2)}M`;
}

async function main() {
  if (!process.env.SUPABASE_DB_URL) throw new Error("SUPABASE_DB_URL not set");
  const c = new Client({
    connectionString: process.env.SUPABASE_DB_URL,
    ssl: { rejectUnauthorized: false },
  });
  await c.connect();
  try {
    const { rows: signals } = await c.query<Signal>(
      "select id, plan_id, fields, commitment_amount_usd, confidence, prompt_version, document_id, created_at from signals where signal_type = 1",
    );
    const { rows: plans } = await c.query<Plan>("select id, name from plans");
    const planNameById = new Map(plans.map((p) => [p.id, p.name]));

    // ── GP-frequency map (used for Q3 canonical heuristic).
    const gpFreq = new Map<string, number>();
    for (const s of signals) {
      const gp = gpOf(s);
      if (gp) gpFreq.set(gp, (gpFreq.get(gp) ?? 0) + 1);
    }

    // ── Q2: same plan+gp+amount, distinct fund_name.
    type Q2Group = {
      plan_id: string;
      gp: string;
      amount: number | null;
      variants: Map<string, Signal[]>;
    };
    const q2Map = new Map<string, Q2Group>();
    for (const s of signals) {
      const amt = s.commitment_amount_usd == null ? null : Number(s.commitment_amount_usd);
      const key = [s.plan_id, gpOf(s), amt ?? "null"].join("|");
      let g = q2Map.get(key);
      if (!g) {
        g = { plan_id: s.plan_id, gp: gpOf(s), amount: amt, variants: new Map() };
        q2Map.set(key, g);
      }
      const fund = fundOf(s);
      if (!g.variants.has(fund)) g.variants.set(fund, []);
      g.variants.get(fund)!.push(s);
    }
    const q2Cases = Array.from(q2Map.values())
      .filter((g) => g.variants.size > 1)
      .sort((a, b) => (b.amount ?? 0) - (a.amount ?? 0));

    // ── Q3: same plan+fund_name+amount, distinct gp.
    type Q3Group = {
      plan_id: string;
      fund: string;
      amount: number | null;
      variants: Map<string, Signal[]>;
    };
    const q3Map = new Map<string, Q3Group>();
    for (const s of signals) {
      const amt = s.commitment_amount_usd == null ? null : Number(s.commitment_amount_usd);
      const key = [s.plan_id, fundOf(s), amt ?? "null"].join("|");
      let g = q3Map.get(key);
      if (!g) {
        g = { plan_id: s.plan_id, fund: fundOf(s), amount: amt, variants: new Map() };
        q3Map.set(key, g);
      }
      const gp = gpOf(s);
      if (!g.variants.has(gp)) g.variants.set(gp, []);
      g.variants.get(gp)!.push(s);
    }
    const q3Cases = Array.from(q3Map.values())
      .filter((g) => g.variants.size > 1)
      .sort((a, b) => (b.amount ?? 0) - (a.amount ?? 0));

    console.log(`Q2 cases (post Q1 cleanup): ${q2Cases.length}`);
    console.log(`Q3 cases (post Q1 cleanup): ${q3Cases.length}`);

    // ── Build markdown doc.
    const lines: string[] = [];
    lines.push("# Dedupe near-duplicates audit - 2026-04-26");
    lines.push("");
    lines.push("Generated by `scripts/dedupe-near-dups-doc.ts` after the Q1 exact-duplicate cleanup landed (116 rows deleted, T1 commitment count went 479 -> 363). This audit covers the remaining near-duplicate cases that need per-case judgment.");
    lines.push("");
    lines.push(`Total cases: **${q2Cases.length + q3Cases.length}** (${q2Cases.length} Q2 fund_name variants + ${q3Cases.length} Q3 gp variants).`);
    lines.push("");
    lines.push("Cases are sorted by amount descending. Stop reviewing at any point and the remaining cases will be the smallest dollar amounts.");
    lines.push("");
    lines.push("## How to fill this in");
    lines.push("");
    lines.push("For each case below the YAML block, mark a decision in the YAML:");
    lines.push("");
    lines.push("- `decision: merge` - all variants are the same fund / gp; collapse them. Pick the canonical variant by index.");
    lines.push("- `decision: keep_distinct` - the variants are different things. Keep all rows.");
    lines.push("");
    lines.push("`canonical` is the 1-indexed variant number to keep when merging. Ignored when `decision: keep_distinct`.");
    lines.push("");
    lines.push("`notes` is optional. Use it for context if the case is unusual.");
    lines.push("");
    lines.push("When done, run `pnpm tsx scripts/dedupe-q23-cleanup.ts --apply` (script to be added in step 5).");
    lines.push("");
    lines.push("## Decisions");
    lines.push("");
    lines.push("```yaml");

    // YAML block: one entry per case.
    const yamlBlock: string[] = [];
    q2Cases.forEach((g, i) => {
      const id = `Q2-${String(i + 1).padStart(3, "0")}`;
      const variants = Array.from(g.variants.keys());
      const longest = variants.reduce((a, b) => (b.length > a.length ? b : a), variants[0]);
      const suggested = variants.indexOf(longest) + 1;
      yamlBlock.push(`${id}:`);
      yamlBlock.push(`  decision: merge   # or keep_distinct`);
      yamlBlock.push(`  canonical: ${suggested}   # 1-indexed; suggested = longest variant`);
      yamlBlock.push(`  notes: ""`);
    });
    q3Cases.forEach((g, i) => {
      const id = `Q3-${String(i + 1).padStart(3, "0")}`;
      const variants = Array.from(g.variants.keys());
      const suggested =
        variants
          .map((v, idx) => ({ v, idx, freq: gpFreq.get(v) ?? 0 }))
          .sort((a, b) => b.freq - a.freq)[0]?.idx ?? 0;
      yamlBlock.push(`${id}:`);
      yamlBlock.push(`  decision: merge   # or keep_distinct`);
      yamlBlock.push(`  canonical: ${suggested + 1}   # 1-indexed; suggested = most-frequently-used gp variant globally`);
      yamlBlock.push(`  notes: ""`);
    });
    lines.push(...yamlBlock);
    lines.push("```");
    lines.push("");

    // Q2 narrative section.
    lines.push("## Q2 cases (fund_name variants)");
    lines.push("");
    lines.push("Same plan + same gp + same amount, but distinct `fund_name` strings. Common families: legal-suffix differences, abbreviation vs full name, and genuinely different funds the same gp closed at the same dollar amount.");
    lines.push("");
    q2Cases.forEach((g, i) => {
      const id = `Q2-${String(i + 1).padStart(3, "0")}`;
      const planName = planNameById.get(g.plan_id) ?? g.plan_id;
      lines.push(`### ${id} - ${planName} - ${g.gp} - ${fmtAmt(g.amount)}`);
      lines.push("");
      const variants = Array.from(g.variants.entries());
      const longest = variants.reduce((a, b) => (b[0].length > a[0].length ? b : a), variants[0]);
      variants.forEach(([fund, rows], idx) => {
        const ids = rows.map((r) => r.id.slice(0, 8)).join(", ");
        const dates = rows.map((r) => dateStr(r.created_at)).join(", ");
        const conf = rows.map((r) => Number(r.confidence ?? 0).toFixed(2)).join(", ");
        const star = fund === longest[0] ? " (suggested canonical)" : "";
        lines.push(`- **${idx + 1}**: \`"${fund}"\`${star} - ${rows.length} row(s), ids=[${ids}], created=[${dates}], conf=[${conf}]`);
      });
      lines.push("");
    });

    // Q3 narrative section.
    lines.push("## Q3 cases (gp variants)");
    lines.push("");
    lines.push("Same plan + same `fund_name` + same amount, but distinct gp strings. Common families: brand vs legal entity, brand vs strategy line, and post-acquisition-rebrand cases (e.g. Angelo Gordon -> TPG Angelo Gordon).");
    lines.push("");
    q3Cases.forEach((g, i) => {
      const id = `Q3-${String(i + 1).padStart(3, "0")}`;
      const planName = planNameById.get(g.plan_id) ?? g.plan_id;
      lines.push(`### ${id} - ${planName} - "${g.fund}" - ${fmtAmt(g.amount)}`);
      lines.push("");
      const variants = Array.from(g.variants.entries());
      const ranked = variants.map(([gp]) => ({ gp, freq: gpFreq.get(gp) ?? 0 }));
      const suggestedGp = ranked.sort((a, b) => b.freq - a.freq)[0]?.gp;
      variants.forEach(([gp, rows], idx) => {
        const ids = rows.map((r) => r.id.slice(0, 8)).join(", ");
        const dates = rows.map((r) => dateStr(r.created_at)).join(", ");
        const conf = rows.map((r) => Number(r.confidence ?? 0).toFixed(2)).join(", ");
        const freq = gpFreq.get(gp) ?? 0;
        const star = gp === suggestedGp ? " (suggested canonical)" : "";
        lines.push(`- **${idx + 1}**: \`"${gp}"\`${star} - global freq=${freq}, ${rows.length} row(s) here, ids=[${ids}], created=[${dates}], conf=[${conf}]`);
      });
      lines.push("");
    });

    const outPath = "/Users/vitekvrana/Desktop/lp-signal/docs/audits/dedupe-near-dupes-2026-04-26.md";
    fs.writeFileSync(outPath, lines.join("\n"));
    console.log(`wrote ${outPath} (${lines.length} lines)`);
  } finally {
    await c.end();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
